-- migrations/003_config.sql

CREATE TABLE IF NOT EXISTS config_kv (
  k VARCHAR(128) NOT NULL PRIMARY KEY,
  v JSON NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;