--[[
    -- Type: Client Script
    -- Name: empty.lua
    -- Use: Forces scheduler.lua to load client-side enabling remote callbacks
    -- Created: 2024-06-04
    -- By: VSSVSSN
--]]

--[[
    -- The file intentionally contains no runtime code.
    -- Its presence triggers client initialization of scheduler.lua,
    -- allowing callbacks to function bi-directionally between
    -- server and client.
--]]