-- resources/sunnyrp/economy/client/main.lua
RegisterNUICallback('atm:deposit', function(data, cb)
  TriggerServerEvent('srp:atm:deposit', tonumber(data.amount or 0))
  cb({ ok = true })
end)
RegisterNUICallback('atm:withdraw', function(data, cb)
  TriggerServerEvent('srp:atm:withdraw', tonumber(data.amount or 0))
  cb({ ok = true })
end)

-- Example keybind to open ATM (replace with marker proximity in your map manager)
RegisterCommand('atm', function()
  SetNuiFocus(true, true)
  SendNUIMessage({ type='atm:open' })
end)