CREATE TABLE IF NOT EXISTS weather_state (
  id TINYINT PRIMARY KEY,
  weather VARCHAR(16) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT IGNORE INTO weather_state (id, weather) VALUES (1, 'CLEAR');
