CREATE TABLE IF NOT EXISTS rcon_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  command VARCHAR(128) NOT NULL,
  args TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exec_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  code TEXT NOT NULL,
  output TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restart_schedule (
  id TINYINT PRIMARY KEY,
  restart_at TIMESTAMP NOT NULL,
  reason VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS debug_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
