CREATE TABLE IF NOT EXISTS assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  owner_id BIGINT NOT NULL,
  url VARCHAR(1024) NOT NULL,
  type VARCHAR(100) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_assets_owner ON assets(owner_id);
