CREATE TABLE IF NOT EXISTS character_peds (
  character_id BIGINT PRIMARY KEY,
  model VARCHAR(60) NOT NULL,
  health INT NOT NULL,
  armor INT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_character_peds_character FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
